version: '3'
services:
  api-gateway:
    image: api-gateway-image
    ports:
    - "8080:8080"
  demo:
    image: demo-image
    ports:
    - "7777:7777"
  discovery-service:
    image: discovery-service--image
    ports:
    - "8761:8761"